require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  # All cops except the ones in disabled.yml are enabled.
  Exclude:
    - "vendor/bundle/**/*"
    - "vendor/bin/**/*"
    - ",/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "config/initializers/*"

Metrics/LineLength:
  Max: 120
  Exclude:
    - "app/views/**/*"
    - "config/**/*.rb"
    - "spec/factories/**/*.rb"

Metrics/BlockLength:
  Enabled: false

Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  Enabled: true

Style/MixinGrouping:
  Enabled: true
  Exclude:
    - 'rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/**/*_spec.rb'
Rails:
  Enabled: true

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - 'spec/requests/**/*_spec.rb'
    - 'spec/features/**/*_spec.rb'
    - 'spec/system/**/*_spec.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
